apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bookservice
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: bookservice
        microservice-type: api
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gcp.creds
      containers:
      - name: bookservice
        image: gcr.io/hafslund-istio-test/github-sheitm-istio-test-bookservice:1.0.1
        imagePullPolicy: Always
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/datastore